# What is Numpy


NumPy, which stands for "Numerical Python," is a fundamental Python library for numerical and scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. NumPy is a core library for data manipulation and analysis in the field of data science, machine learning, and scientific research.

In [3]:
import numpy as np

In [7]:
x = np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [8]:
x = [1,2,3,4]
print(x)
print(type(x))

[1, 2, 3, 4]
<class 'list'>


# Array

### Create array 

In [15]:
lst = []
for i in range(1,5):
    x = input("Enter the element of list")
    lst.append(x)
print(np.array(lst))    

Enter the element of list65
Enter the element of list32
Enter the element of list45
Enter the element of list87
['65' '32' '45' '87']


If we Enter in input it treated like String


In [16]:
lst = []
for i in range(1,5):
    x = int(input("Enter the element of list: "))
    lst.append(x)
y = np.array(lst) 
print(y)
print(type(y))

Enter the element of list: 2
Enter the element of list: 4
Enter the element of list: 6
Enter the element of list: 8
[2 4 6 8]
<class 'numpy.ndarray'>


### Array types 

1D Array
2D Array
3D Array
Multi Dimensional Array

###  To check array dimension .ndim

In [22]:
lst = []
for i in range(1,5):
    x = int(input("Enter the element of list: "))
    lst.append(x)
y = np.array(lst) 
print("Array dimension ",y.ndim)

Enter the element of list: 4
Enter the element of list: 3
Enter the element of list: 2
Enter the element of list: 1
Array dimension  1


## 2D Array 

In [23]:
two_d = [[1,2,3,4],[7,8,9,3]]
y = np.array(two_d)
print(y)
print(y.ndim)

[[1 2 3 4]
 [7 8 9 3]]
2


In [24]:
two_d = [[1,2,3,4],[7,8,9]]
y = np.array(two_d)
print(y)
print(y.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In 2D Array element is same in each 1D array otherwise it gives error

## 3D Array 

In [25]:
tree_d = [[[1,2,3],[5,6,7],[8,3,5],[5,3,6]]]
y = np.array(tree_d)
print(y)
print(y.ndim)

[[[1 2 3]
  [5 6 7]
  [8 3 5]
  [5 3 6]]]
3


## Multi Dimensional Array ndmin

In [26]:
mda = np.array([1,2,3,4],ndmin = 10)
print(mda)
print(mda.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Spacial Numpy Array

Array Filled with 0's
Array Filled with 1's
Create a empty array
An array with a range of element
Array diagonal element filled with 1's
Create an array with values that are spaced linearly in a speadified interval

In [27]:
#Array Filled with 0's
val_zero = np.zeros(4)
print(val_zero)

[0. 0. 0. 0.]


In [28]:
#Array Filled with 0's 2D dim
val_zero = np.zeros((4,3))
print(val_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [30]:
#Array Filled with 1's
val_one = np.ones(5)
print(val_one)

[1. 1. 1. 1. 1.]


In [32]:
#Array Filled with 1's  2D dim
val_one = np.ones((3,4))
print(val_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [2]:
#Array Filled with 1's  2D dim
import numpy as np
val_one = np.ones(3,4,ndmin = 4)
print(val_one)

TypeError: ones() got an unexpected keyword argument 'ndmin'


The error you're encountering is because the np.ones function doesn't have an ndmin parameter.
The np.ones function is used to create an array filled with 1's of a specified shape, but you 
should provide the shape as a single tuple, not as separate arguments. Here's how you can fix 
the error:



In [39]:

# Create a 3D array filled with 1's of shape (2, 3, 4)
# This will create a 3D array with 2 "layers," each having 3 rows and 4 columns.
array_3d = np.ones((2, 3, 4))

print(array_3d)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


## Empty array

In [40]:
ar_em = np.empty(5)
print(ar_em)

[1. 1. 1. 1. 1.]


empty array take previous memory data

## Range

In [43]:
ar_rng = np.arange(4) # if we not starting position then it take 0 is default
print(ar_rng)

[0 1 2 3]


In [45]:
ar_rng = np.arange(1,4)
print(ar_rng)

[1 2 3]


## Diagonal 

In [47]:
ar_dia = np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [49]:
ar_dia = np.eye(4,4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [51]:
ar_dia = np.eye(5,4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [55]:
ar_dia = np.eye(4,8)
print(ar_dia)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


## linspace 

In [59]:
ar_line = np.linspace(0,20, num = 5)
print(ar_line)

[ 0.  5. 10. 15. 20.]


## Create Numpy array with Random Numbers 

## Random 

### rand() 

np.random.rand(shape): Generates random numbers from a uniform distribution in the interval [0, 1]. The shape argument specifies the dimensions of the output array.
import numpy as np
random_array = np.random.rand(2, 3)  # 2x3 array of random numbers between 0 and 1

In [60]:
ar_rn = np.random.rand(5)
print(ar_rn)

[0.18465083 0.79619303 0.55886527 0.34701495 0.17399696]


In [61]:
ar_rn = np.random.rand(10)
print(ar_rn)

[0.08177787 0.04916602 0.05475248 0.08577576 0.91867193 0.78366361
 0.77350221 0.26794694 0.57710619 0.29731882]


In [63]:
# 2D Random array range 0 to 1
ar_rn = np.random.rand(2,5)
print(ar_rn)

[[0.03744263 0.27135791 0.78614575 0.55648247 0.06143631]
 [0.77465045 0.44612361 0.40018435 0.0662253  0.71053745]]


## randn()

np.random.randn(shape): Generates random numbers from a standard normal (Gaussian) distribution with mean 0 and standard deviation 1.


import numpy as np
random_array = np.random.randn(3, 4)  # 3x4 array of random numbers from a standard normal distribution

In [64]:
var = np.random.randn(5)
print(var)

[ 0.03470717 -2.7276999  -0.6077187  -0.50085121 -0.44636657]


In [65]:
var = np.random.randn(3,4)
print(var)

[[-1.81411841 -0.19265465 -1.57289732  0.44026196]
 [ 0.85332179  0.40403475 -1.70912803 -0.23105647]
 [ 1.15866696  1.15651806 -0.34492604  0.80924611]]


## ranf() 

numpy.random.random are functions used to generate random numbers from a uniform distribution over the interval [0, 1)

In [66]:
var = np.random.ranf(5)

print(var)

[0.86914852 0.54329801 0.16059278 0.28751873 0.61152565]


## randint 

In NumPy, the numpy.random.randint function is used to generate random integers within a specified range. You can use this function to create arrays of random integers. Here's the basic syntax:


numpy.random.randint(low, high=None, size=None, dtype='l')
low: The lowest (inclusive) integer in the range.
high: The highest (exclusive) integer in the range. If not provided, it defaults to one above low.
size: The shape of the output array. If not provided, a single random integer is generated.
dtype: The data type of the output array. It's optional and defaults to 'int64' ('l' stands for long integer).
Here are some examples of how to use numpy.random.randint:


import numpy as np


rand_int = np.random.randint(10)
print(rand_int)

rand_int = np.random.randint(5, 16)
print(rand_int)

rand_array_1d = np.random.randint(1, 101, size=5)
print(rand_array_1d)

rand_array_2d = np.random.randint(-10, 11, size=(3, 4))
print(rand_array_2d)
Keep in mind that the low value is inclusive, while the high value is exclusive. In other words, the generated random integers can include low but not high. Also, the random integers are generated using a pseudorandom number generator and can be controlled using the random seed with numpy.random.seed for reproducibility.

In [69]:
var = np.random.randint(5 , 20, 5, dtype='l')
print(var)

[10  5  9 14  6]


In [70]:
# Generate a random integer between 0 and 9
rand_int = np.random.randint(10)
print(rand_int)


5


In [71]:
# Generate a random integer between 5 and 15
rand_int = np.random.randint(5, 16)
print(rand_int)

14


In [72]:
# Generate a 1D array of 5 random integers between 1 and 100
rand_array_1d = np.random.randint(1, 101, size=5)
print(rand_array_1d)

[62 24 38 55 58]


In [75]:
# Generate a 2D array of shape (3, 4) with random integers between -10 and 10
rand_array_2d = np.random.randint(10, 31, size=(3, 4))
print(rand_array_2d)

[[21 11 30 20]
 [29 23 11 22]
 [30 29 12 20]]


In [77]:
# Generate a 2D array of shape (3, 4) with random integers between -10 and 10
rand_array_2d = np.random.randint(-10, 11, 4)
print(rand_array_2d)

[-9  7  0 -1]


# Data Type Numpy Array

In [ ]:
Data Type	Code	Description
int8	'int8'	8-bit signed integer
int16	'int16'	16-bit signed integer
int32	'int32'	32-bit signed integer
int64	'int64'	64-bit signed integer
uint8	'uint8'	8-bit unsigned integer
uint16	'uint16'	16-bit unsigned integer
uint32	'uint32'	32-bit unsigned integer
uint64	'uint64'	64-bit unsigned integer
float16	'float16'	16-bit floating-point number (half-precision)
float32	'float32'	32-bit floating-point number (single-precision)
float64	'float64'	64-bit floating-point number (double-precision)
complex64	'complex64'	Complex number with two 32-bit floats (real and imaginary parts)
complex128	'complex128'	Complex number with two 64-bit floats (real and imaginary parts)
bool	'bool'	Boolean (True/False)
object	'object'	Python object (generic data type)
string (fixed size)	'S'	String with fixed size
string (variable size)	'U'	Unicode string with variable size

In [78]:
var = np.array([1,2,3,4,5])

print(var.dtype)

int64


In [81]:
var = np.array([1,2])

print(var.dtype)

int64


In [82]:
var = np.array([1,2,3,4,555555])

print(var.dtype)

int64


In [83]:
var = np.array([1.9,2.6,3,4,5])

print(var.dtype)

float64


In [84]:
var = np.array(['s','h','b'])

print(var.dtype)

<U1


##### What is  <U1 

In [ ]:
The <U1 data type code represents a Unicode string of 1 character. In other words, 
it's a one-character Unicode string. This is the default data type inferred by NumPy
when you create an array of single-character strings.

Here's a breakdown of what <U1 means:

<: Indicates little-endian byte order (the default for most platforms).
U: Indicates Unicode string.
1: Specifies the length of the string in characters, which in this case is 1 character.
So, when you create a NumPy array with single-character strings, NumPy assigns 
the <U1 data type to that array to represent each element as a one-character Unicode string.

In [85]:
var = np.array(['Shahbaz','alam'])

print(var.dtype)

<U7


<: Indicates little-endian byte order (the default for most platforms).
U: Indicates Unicode string.
7: Specifies the length of the string in characters, which in this case is 7 characters.

In [86]:
var = np.array(['Shahbazzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz','alam'])

print(var.dtype)

<U37


In [ ]:
Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [87]:
var = np.array([1,2,5,6,7])

print(var.dtype)

int64


In [88]:
var = np.array([1,2,5,6,7,9],dtype = int8)

print(var.dtype)

NameError: name 'int8' is not defined

In [89]:
var = np.array([1,2,5,6,7,9],dtype = np.int8)

print(var.dtype)

int8


In [94]:
var = np.array([1,2,5,6,7,9],dtype = np.int32)
print(var)
print(var.dtype)

[1 2 5 6 7 9]
int32


In [95]:
var = np.array([1,2,5,6,7,9],dtype =  'f')
print(var)
print(var.dtype)

[1. 2. 5. 6. 7. 9.]
float32


In [96]:
# convert int to float using float function
var = np.array([1,2,5,6,7,9])

new = np.float32(var)

print(var.dtype)
print(new.dtype)
print(var)
print(new)

int64
float32
[1 2 5 6 7 9]
[1. 2. 5. 6. 7. 9.]


In [98]:
var = np.array([1.3,2.54,5,6,7,9])
new = np.int16(var)
print(var.dtype)
print(new.dtype)
print(var)
print(new)

float64
int16
[1.3  2.54 5.   6.   7.   9.  ]
[1 2 5 6 7 9]


In [100]:
# here we convert float to int and int to float same data
var = np.array([1.3,2.54,5,6,7,9])
new = np.int16(var)
old = np.float64(new)
print(var.dtype)
print(new.dtype)
print(old.dtype)
print(var)
print(new)
print(old)

float64
int16
float64
[1.3  2.54 5.   6.   7.   9.  ]
[1 2 5 6 7 9]
[1. 2. 5. 6. 7. 9.]


#### astype   to convert data type of numpy

In [104]:
# here we convert float to int and int to float same data
var = np.array([1.3,2.54,5,6,7,9])
new = var.astype(int)
old = new.astype(float)
print(var.dtype)
print(new.dtype)
print(old.dtype)
print(var)
print(new)
print(old)

float64
int64
float64
[1.3  2.54 5.   6.   7.   9.  ]
[1 2 5 6 7 9]
[1. 2. 5. 6. 7. 9.]


## Shape And Reshape of numpy array 

### Shape

In [105]:
var = np.array([1,2,3,4,])
print(var)

[1 2 3 4]


In [106]:
var = np.array([1,2,3,4,])
print(var)
print(var.shape)

[1 2 3 4]
(4,)


In [107]:
var = np.array([[1,2,3,4,],[1,2,3,4,]])

print(var)
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]
(2, 4)


In [109]:
var = np.array([1,2,3,4,5,6], ndmin = 4)

print(var)
print(var.ndim)
print(var.shape)

[[[[1 2 3 4 5 6]]]]
4
(1, 1, 1, 6)


1,1,1 represent row, means three row and 6 represent col one column

## Reshape 

In [110]:
var = np.array([1,2,3,4,5,6])
new = var.reshape(3,2)
print(var)
print(var.ndim)
print(new)
print(new.ndim)

[1 2 3 4 5 6]
1
[[1 2]
 [3 4]
 [5 6]]
2


In [111]:
var = np.array([1,2,3,4,5,6])
new = var.reshape(3,3)
print(var)
print(var.ndim)
print(new)
print(new.ndim)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [113]:
var = np.array([1,2,3,4,5,6,4,5,8])
new = var.reshape(3,3)
print(var)
print(var.ndim)
print(new)
print(new.ndim)

[1 2 3 4 5 6 4 5 8]
1
[[1 2 3]
 [4 5 6]
 [4 5 8]]
2


In [4]:
var = np.array([1,2,3,4,5,6,4,5,8,9,10,11,12,13,14,1,5,16,17,18,19,20,21,22])
new = var.reshape(2,3,4) # x-axis =2 row, y axis = 3 column, z axis = 4
# ** Refer on this link for better understanding, remove # in starting
#https://www.google.com/search?q=3d+numpy+array&sca_esv=571840155&tbm=isch&sxsrf=AM9HkKlzaWZUqiDgRiDWpPJvRrCmoC32eA:1696842402875&source=lnms&sa=X&sqi=2&ved=2ahUKEwioxqbFzuiBAxW7zjgGHXgEBpMQ_AUoAnoECAEQBA&biw=1440&bih=783&dpr=2#imgrc=VC7l8pq8AbQr1M

print(var)
print(var.ndim)
print(new)
print(new.ndim)

[ 1  2  3  4  5  6  4  5  8  9 10 11 12 13 14  1  5 16 17 18 19 20 21 22]
1
[[[ 1  2  3  4]
  [ 5  6  4  5]
  [ 8  9 10 11]]

 [[12 13 14  1]
  [ 5 16 17 18]
  [19 20 21 22]]]
3


In a 3D NumPy array with dimensions (2, 3, 4), the size represents the total number of elements in the array. To calculate the size, you can multiply the sizes of each dimension together. In this case:

Size = 2 (dimension along the first axis) * 3 (dimension along the second axis) * 4 (dimension along the third axis)

Size = 2 * 3 * 4 = 24

So, the size of a 3D NumPy array with dimensions (2, 3, 4) is 24. This means there are 24 elements in the array when you consider all three dimensions.

In [3]:
#1D to 3D to 1D
var = np.array([1,2,3,4,5,6,4,5,8,9,10,11,12,13,14,1,5,16,17,18,19,20,21,22])
new = var.reshape(2,3,4) # x-axis =2 row, y axis = 3 column, z axis = 4

old = new.reshape(-1)

print(var)
print(var.ndim)
print(new)
print(new.ndim)
print(old)
print(old.ndim)

[ 1  2  3  4  5  6  4  5  8  9 10 11 12 13 14  1  5 16 17 18 19 20 21 22]
1
[[[ 1  2  3  4]
  [ 5  6  4  5]
  [ 8  9 10 11]]

 [[12 13 14  1]
  [ 5 16 17 18]
  [19 20 21 22]]]
3
[ 1  2  3  4  5  6  4  5  8  9 10 11 12 13 14  1  5 16 17 18 19 20 21 22]
1


## Arithematic operator in Numpy array 

In [5]:
import numpy as np
var = np.array([1,2,3,4])
var_add = var + 3 # add 3 in each element
print(var_add)

[4 5 6 7]


In [6]:
import numpy as np
var = np.array([1,2,3,4])
var_add = var - 3 # subtract 3 in each element
print(var_add)

[-2 -1  0  1]


In [7]:
import numpy as np
var = np.array([1,2,3,4])
var_add = var * 3 # mul 3 in each element
print(var_add)

[ 3  6  9 12]


In [8]:
import numpy as np
var = np.array([1,2,3,4])
var_add = var / 3 # add 3 in each element
print(var_add)

[0.33333333 0.66666667 1.         1.33333333]


In [9]:
import numpy as np
var = np.array([5,9,10,30,50])
var_add = var / 3 # add 3 in each element
print(var_add)

[ 1.66666667  3.          3.33333333 10.         16.66666667]


In [12]:
import numpy as np
var = np.array([5,9,10,30,50])
var_add = var % 3 # mod 3 in each element
print(var_add)

[2 0 1 0 2]


In [13]:
import numpy as np
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

var_add = var1 + var2 # add 3 in each element
print(var_add)

[2 4 6 8]


In [18]:

import numpy as np
var1 = np.array([11,21,31,41])

var_add = np.add(var1,3)
print(var_add)

[14 24 34 44]


In [14]:

import numpy as np
var1 = np.array([11,21,31,41])
var2 = np.array([1,2,3,4])

var_add = var1 - var2 # add 3 in each element
print(var_add)

[10 19 28 37]


In [20]:

import numpy as np
var1 = np.array([11,21,31,41])
var_add = np.subtract(var1, 3)
print(var_add)

[ 8 18 28 38]


In [15]:

import numpy as np
var1 = np.array([11,21,31,41])
var2 = np.array([1,2,3,4])

var_add = var1 * var2 # add 3 in each element
print(var_add)

[ 11  42  93 164]


In [21]:

import numpy as np
var1 = np.array([11,21,31,41])
var_add = np.multiply(var1, 3)
print(var_add)

[ 33  63  93 123]


In [16]:

import numpy as np
var1 = np.array([11,21,31,41])
var2 = np.array([1,2,3,4])

var_add = var1 / var2 # add 3 in each element
print(var_add)

[11.         10.5        10.33333333 10.25      ]


In [22]:

import numpy as np
var1 = np.array([11,21,31,41])
var_add = np.divide(var1, 3)
print(var_add)

[ 3.66666667  7.         10.33333333 13.66666667]


In [17]:

import numpy as np
var1 = np.array([11,21,31,41])
var2 = np.array([1,2,3,4])

var_add = var1 % var2 # add 3 in each element
print(var_add)

[0 1 1 1]


In [23]:

import numpy as np
var1 = np.array([11,21,31,41])
var_add = np.mod(var1, 3)
print(var_add)

[2 0 1 2]


In [24]:
# Reciprocal
import numpy as np
var1 = np.array([11,21,31,41])
var_add = np.reciprocal(var1,3)
print(var_add)

TypeError: return arrays must be of ArrayType

In [27]:
# Reciprocal
import numpy as np
var1 = np.array([11,21,31,41])
var_add = np.reciprocal(var1)
print(var_add)

[0 0 0 0]


In [29]:
# Reciprocal
import numpy as np
var1 = np.array([1.0,2.3,3.1,4.9])
var_add = np.reciprocal(var1)
print(var_add)

[1.         0.43478261 0.32258065 0.20408163]


In [30]:
# Reciprocal
import numpy as np
var1 = np.array([11,21,31,41])
var2 = 0.5
var_add = np.reciprocal(var1,var2)
print(var_add)

TypeError: return arrays must be of ArrayType

In [32]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
var_add = var1 + var2
print(var_add)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [33]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
# var_add = var1 + var2
var_add = np.add(var1, var2)
print(var_add)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[2 4 6 8]
 [2 4 6 8]]


In [34]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
# var_add = var1 - var2
var_add = np.subtract(var1,var2)
print(var_add)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[0 0 0 0]
 [0 0 0 0]]


In [35]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
# var_add = var1 * var2
var_add = np.multiply(var1, var2)
print(var_add)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


In [36]:
var1 = np.array([[11,21,31,41],[21,22,23,24]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
# var_add = var1 / var2
var_add = np.divide(var1,var2)
print(var_add)

[[11 21 31 41]
 [21 22 23 24]]

[[1 2 3 4]
 [1 2 3 4]]

[[11.         10.5        10.33333333 10.25      ]
 [21.         11.          7.66666667  6.        ]]


In [37]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
var_add = var1 % var2
print(var_add)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[0 0 0 0]
 [0 0 0 0]]


In [38]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
var2 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
print(var2)
print()
# var_add = var1 % var2
var_add = np.mod(var1, var2)
print(var_add)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[0 0 0 0]
 [0 0 0 0]]


# Arithmetic Function

In [40]:
var = np.array([12,23,3,45])

var_add = np.min(var)
print("Mini value is: ",var_add)

Mini value is:  3


In [41]:
var = np.array([12,23,3,45])

var_add = np.max(var)
print("Maxi value is: ",var_add)

Maxi value is:  45


#### For index of minimum & maximum 

In [43]:
var = np.array([12,23,3,45,1])

var_add = np.min(var),np.argmin(var)
print("Mini value is: ",var_add)

Mini value is:  (1, 4)


In [44]:
var = np.array([12,23,3,45,1])

var_add = np.max(var),np.argmax(var)
print("Maxi value is: ",var_add)

Maxi value is:  (45, 3)


#### Min Max in 2D  

In [ ]:
# for row = 0
# for col = 1


In [55]:
# for col = 1

# [[12,23,3,45,11], min = 3
#  [67,14,44,67,9]] min = 9
var = np.array([[12,23,3,45,11],[67,14,44,67,9]])
var_add = np.min(var,axis = 1)
print(var_add)

[3 9]


In [56]:
# for row = 0

# [[12,23,3,45,11], min = 3
#  [67,14,44,67,9]] min = 9
var = np.array([[12,23,3,45,11],[67,14,44,67,9]])
var_add = np.min(var,axis = 0)
print(var_add)

[12 14  3 45  9]


### Sqrt 

In [57]:

var = np.array([[12,23,3,45,11],[67,14,44,67,9]])
var_add = np.sqrt(var)
print(var_add)

[[3.46410162 4.79583152 1.73205081 6.70820393 3.31662479]
 [8.18535277 3.74165739 6.63324958 8.18535277 3.        ]]


### Sin & Cos

In [60]:
var = np.array([0,1,2,3])
var_add = np.sin(var)
print(var_add)

[0.         0.84147098 0.90929743 0.14112001]


In [61]:
var = np.array([0,1,2,3])
var_add = np.cos(var)
print(var_add)

[ 1.          0.54030231 -0.41614684 -0.9899925 ]


### cumsum

In [ ]:
In NumPy, you can calculate the cumulative sum of elements in an array using 
the numpy.cumsum() function. The cumulative sum computes the running total of 
elements in the array, where each element in the result is the sum of all the
elements before and including the corresponding element in the original array.
Here's how to use numpy.cumsum():

In this example, cumulative_sum contains the cumulative sum of the elements in 
the arr array. The first element is 1 (the same as in the original array), the 
second element is 1 + 2 = 3, the third element is 1 + 2 + 3 = 6, and so on.

You can also calculate the cumulative sum along a specific axis in a multi-dimensional 
array by specifying the axis parameter in the numpy.cumsum() function

In [63]:
var = np.array([0,1,2,3]) # 0, 0+1 = 1, 1+2 = 3, 3+3 = 6 , first as it is
#[0,1,3,6]
var_add = np.cumsum(var)
print(var_add)

[0 1 3 6]


## Broadcasting  

In [ ]:
The broadcasting rules in NumPy define how arrays with different shapes can be combined 
or operated on together in a way that makes sense. NumPy automatically broadcasts arrays
to match their shapes when performing element-wise operations, making it easier to work 
with arrays of different sizes. The primary broadcasting rule is that two dimensions are 
compatible when:

They are equal.
One of them is 1.
Here's a more detailed explanation of the broadcasting rules in NumPy:

If two arrays have a different number of dimensions, the shape of the smaller-dimensional 
array is padded with ones on the left side to make their shapes compatible.

The sizes of the dimensions are compared element-wise. Starting from the trailing dimensions,
the sizes are considered compatible when they are equal or when one of them is 1.

If the sizes in a dimension don't match and none of them is 1, it results in a "ValueError"
because the arrays cannot be broadcast together.



In [65]:
arr1 = np.array([[1, 2, 3],[4,5,6]])
arr2 = np.array([[10, 20],[1,2],[4,5]])

result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1

print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [69]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10],[20]])

result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1

print(result)

[[11 12 13]
 [21 22 23]]


In [76]:
arr1 = np.array([[1],[4],[5]])
arr2 = np.array([[10],[5]])
print(arr1.shape)
print()
print(arr2.shape)
result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1

print(result)

(3, 1)

(2, 1)


ValueError: operands could not be broadcast together with shapes (3,1) (2,1) 

In [88]:
arr1 = np.array([[1],[4],[5]])
arr2 = np.array([[10],[5],[3]])
print(arr1.shape)
print()
print(arr2.shape)
result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1

print(result)

(3, 1)

(3, 1)
[[11]
 [ 9]
 [ 8]]


In [81]:
arr1 = np.array([1,2])
arr2 = np.array([[10,20],[2,4],[5,10]])
print(arr1.shape)
print()
print(arr2.shape)
# result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1
print(arr1+arr2)
# print(result)

(2,)

(3, 2)
[[11 22]
 [ 3  6]
 [ 6 12]]


In [83]:
arr1 = np.array([[12],[13]])
arr2 = np.array([[10,20,20],[2,4,34]])
print(arr1.shape)
print()
print(arr2.shape)
print()
# result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1
print(arr1+arr2)
# print(result)

(2, 1)

(2, 3)

[[22 32 32]
 [15 17 47]]


In [86]:
arr1 = np.array([[1,2],[2,1],[3,1]])
arr2 = np.array([[10,20],[2,4]])
print(arr1.shape)
print()
print(arr2.shape)
# result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1
print(arr1+arr2)
# print(result)

(3, 2)

(2, 2)


ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [87]:
arr1 = np.array([[1,2],[2,1],[3,1]])
arr2 = np.array([10,20])
print(arr1.shape)
print()
print(arr2.shape)
# result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1
print(arr1+arr2)
# print(result)

(3, 2)

(2,)
[[11 22]
 [12 21]
 [13 21]]


In [89]:
arr1 = np.array([[1,2],[4,2],[5,3]])
arr2 = np.array([2,3,10])
print(arr1.shape)
print()
print(arr2.shape)
result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1

print(result)

(3, 2)

(3,)


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [90]:
arr1 = np.array([1])
arr2 = np.array([2,3,10])
print(arr1.shape)
print()
print(arr2.shape)
result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1

print(result)

(1,)

(3,)
[ 3  4 11]


In [92]:
arr1 = np.array([[10,20],[30,40],[50,60]])
arr2 = np.array([10,20])
print(arr1.shape)
print()
print(arr2.shape)
result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1

print(result)

(3, 2)

(2,)
[[20 40]
 [40 60]
 [60 80]]


In [93]:
arr1 = np.array([[1],[4],[5]])
arr2 = np.array([2,3,10])
print(arr1.shape)
print()
print(arr2.shape)
result = arr1 + arr2  # Broadcasting arr2 to match the shape of arr1

print(result)

(3, 1)

(3,)
[[ 3  4 11]
 [ 6  7 14]
 [ 7  8 15]]


## Indexing 

In [94]:
var = np.array([10,20,30,40])
                #0 ,1, 2 , 3
print(var[2])


30


In [95]:
# negative indeing 
var = np.array([10,20,30,40])
              #-4,-3,-2,-1
print(var[-2])


30


### 2D array index  

To access data in a 2D NumPy array, you can use indexing and slicing. Here's an example of how to access and manipulate data in a 2D array:



In [97]:
# Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Accessing individual elements
print("Value at row 0, column 1:", arr_2d[0, 1])  # Accessing element at row 0, column 1

# Slicing rows and columns
print("First row:", arr_2d[0, :])  # Accessing the first row
print("Second column:", arr_2d[:, 1])  # Accessing the second column

# Slicing sub-arrays
print("Sub-array from rows 0 to 1, columns 1 to 2:")
print(arr_2d[0:2, 1:3])  # Slicing a sub-array from rows 0 to 1 and columns 1 to 2

# Modifying elements
arr_2d[1, 2] = 10  # Modifying element at row 1, column 2
print("Modified array:")
print(arr_2d)

Value at row 0, column 1: 2
First row: [1 2 3]
Second column: [2 5 8]
Sub-array from rows 0 to 1, columns 1 to 2:
[[2 3]
 [5 6]]
Modified array:
[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]


In [ ]:
In this example, we create a 2D NumPy array arr_2d and demonstrate how to access elements 
using indexing and slicing. You can access individual elements using the 
syntax arr_2d[row_index, column_index], and you can slice rows or columns
using arr_2d[start_row:end_row, start_column:end_column]. Modifying elements 
is as simple as assigning a new value to the desired location.

These operations are fundamental for working with data in 2D arrays, and they
can be used in various data analysis, scientific computing, and machine learning tasks.







### 3D numpy array indexing

In [98]:
var = np.array([[[1,2],[6,7]]])
print(var[0,0,1])

2


In [99]:
var = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(var[1,1,2])

6



Creating and working with 3D NumPy arrays involves managing data in a three-dimensional space. You can create, manipulate, and access elements in 3D arrays similarly to 2D arrays. Here's an example demonstrating the creation and basic operations on a 3D array:

In [ ]:
# Create a 3D NumPy array
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]],
                   [[13, 14, 15],
                    [16, 17, 18]]])

# Accessing individual elements
print("Value at position (1, 0, 2):", arr_3d[1, 0, 2])  # Accessing element at position (1, 0, 2)

# Slicing along different axes
print("First 'slice' along the first axis:")
print(arr_3d[0, :, :])  # Accessing the first "slice" along the first axis

print("Second 'slice' along the second axis:")
print(arr_3d[:, 1, :])  # Accessing the second "slice" along the second axis

print("Third 'slice' along the third axis:")
print(arr_3d[:, :, 2])  # Accessing the third "slice" along the third axis

# Modifying elements
arr_3d[2, 1, 0] = 20  # Modifying element at position (2, 1, 0)
print("Modified array:")
print(arr_3d)

In [ ]:
In this example, we create a 3D NumPy array arr_3d and demonstrate how to access elements 
using indexing and slicing along different axes. You can access individual elements using 
the syntax arr_3d[x, y, z], where x, y, and z represent the indices along each dimension.
Slicing works similarly to 2D arrays, but now you have an additional axis to consider.

Understanding how to work with 3D arrays is crucial for various tasks, including image
processing, volumetric data processing, and other applications involving three-dimensional 
data.


### Slicing in numpy 

In [ ]:
Sure, slicing in NumPy is the operation of extracting specific elements from an array. 
It allows you to create views on the original array, which means that the data is not 
copied, and any modifications to the sliced array will affect the original array.
Slicing is performed using the colon (:) operator within square brackets, and it allows
for a versatile way of accessing different parts of the array.

#Here are the key components of slicing in NumPy:

Start, Stop, and Step: The general form of slicing is start:stop:step. These parameters 
are optional and have default values. The start parameter indicates the starting index 
of the slice, the stop parameter indicates the ending index (exclusive), and the step
parameter indicates the step size between elements.

Positive and Negative Indices: NumPy allows the use of negative indices, where -1 refers 
to the last element, -2 refers to the second-to-last element, and so on.

Slicing Multi-dimensional Arrays: For multi-dimensional arrays, you can use slicing
along different axes. For example, you can slice rows, columns, or specific elements 
based on their indices.

Slicing is a powerful tool in NumPy, making it easy to manipulate and extract specific
data from arrays without the need for cumbersome loops or iterations.
It's a fundamental technique for various numerical operations and data processing
tasks in scientific computing and data analysis.

In [100]:
var = np.array([10,20,30,40,50,60,70,80,90,100])
                #0 1, 2 ,3, 4, 5, 6, 7, 8 , 9 
# print(start:stop:step)
print(var[1:8:2])


[20 40 60 80]


In [101]:
# Example of slicing with start, stop, and step
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[2:7])  # Slicing elements from index 2 to 6 (7 is exclusive)
# Output: [3 4 5 6 7]

print(arr[:5])  # Slicing elements from the start to index 4 (5 is exclusive)
# Output: [1 2 3 4 5]

print(arr[2:])  # Slicing elements from index 2 to the end
# Output: [3 4 5 6 7 8 9 10]

print(arr[1:8:2])  # Slicing elements from index 1 to 7 with step size 2
# Output: [2 4 6 8]

[3 4 5 6 7]
[1 2 3 4 5]
[ 3  4  5  6  7  8  9 10]
[2 4 6 8]


####   Positive and Negative Indices:
 

Positive indices refer to the positions of elements from the beginning, starting at 0. Negative indices count from the end, with -1 being the last element, -2 being the second-to-last element, and so forth.



In [102]:
arr = np.array([11, 12, 13, 14, 15])

# Example of positive and negative indices
print(arr[1])  # Accessing element at index 1
# Output: 12

print(arr[-1])  # Accessing the last element
# Output: 15

12
15


####  Slicing Multi-dimensional Arrays:
 

In [104]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Slicing rows and columns
print(arr_2d[1])  # Accessing the second row
# Output: [5 6 7 8]
print()
print(arr_2d[:, 2])  # Accessing the third column
# Output: [3 7 11]
print()
print(arr_2d[0:2, 1:3])  # Slicing a sub-array from the first two rows and the second and third columns
# Output:
# [[2 3]
#  [6 7]]
print()
# Using step in slicing
print(arr_2d[::2, ::2])  # Slicing every other row and every other column
# Output:
# [[1 3]
#  [9 11]]
print()
# Modifying elements through slicing
arr_2d[1:, 1:3] = 0  # Setting elements in the second and third rows, and second and third columns to 0
print(arr_2d)
# Output:
# [[1 2 3 4]
#  [5 0 0 8]
#  [9 0 0 12]]


[5 6 7 8]

[ 3  7 11]

[[2 3]
 [6 7]]

[[ 1  3]
 [ 9 11]]

[[ 1  2  3  4]
 [ 5  0  0  8]
 [ 9  0  0 12]]


In [105]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(arr_2d[1,1:])

[6 7 8]


In [106]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(arr_2d[5,1:])

[10 11 12]


## Iteration in numpy 

In [107]:
var = np.array([1,2,3,4,5,6,7,8,9])
for i in var:
    print(i)

1
2
3
4
5
6
7
8
9


In [109]:
var = np.array([[1,2,3,4],[5,6,7,8]])
print(var)

[[1 2 3 4]
 [5 6 7 8]]


In [111]:
var = np.array([[1,2,3,4],[5,6,7,8]])
print(var)

for i in var:
    for j in i:
        print(j)
    print()    

[[1 2 3 4]
 [5 6 7 8]]
1
2
3
4

5
6
7
8



In [118]:
var = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[2,4,5,7,9]]])
print(var.ndim)
print()
print(var)
print()
for i in var:
    for j in i:
        for k in j:
            print(k)
        print()
    

3

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [ 2  4  5  7  9]]]

1
2
3
4
5

6
7
8
9
10

11
12
13
14
15

2
4
5
7
9



In [121]:
var = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[2,4,5,7,9]]])

print(var.ndim)
print()
for i in np.nditer(var):
    print(i)

3

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
2
4
5
7
9


In [125]:
var = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[2,4,5,7,9]]])

for i in np.nditer(var, flags = ['buffered'], op_dtypes = 'S'):
    print(i) 
print(var.dtype)    

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'
b'13'
b'14'
b'15'
b'2'
b'4'
b'5'
b'7'
b'9'
int64


In [129]:
var = np.array([10,20,30,40,50])
for val,index in np.ndenumerate(var):
    print(val,index)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50


In [130]:
var = np.array([[11,23,45,67],[45,32,13,40]])
for val,index in np.ndenumerate(var):
    print(val,index)

(0, 0) 11
(0, 1) 23
(0, 2) 45
(0, 3) 67
(1, 0) 45
(1, 1) 32
(1, 2) 13
(1, 3) 40


In [131]:
var = np.array([[[11,23,45,67],[45,32,13,40]]])
for val,index in np.ndenumerate(var):
    print(val,index)

(0, 0, 0) 11
(0, 0, 1) 23
(0, 0, 2) 45
(0, 0, 3) 67
(0, 1, 0) 45
(0, 1, 1) 32
(0, 1, 2) 13
(0, 1, 3) 40


### copy & view 

In [132]:
var = np.array([15,8,3,5,90])
cpy = var.copy()
print(var)
print()
print(cpy)

[15  8  3  5 90]

[15  8  3  5 90]


In [133]:
var = np.array([15,8,3,5,90])
vew = var.view()
print(var)
print()
print(vew)

[15  8  3  5 90]

[15  8  3  5 90]


#### diff b/w copy & view 

In [ ]:
#Copy in NumPy:
A copy is a new array that is created in a different location in memory.
It is completely independent of the original array, and changes made to
the copy do not affect the original array.

Modifying the copied array does not affect the original array, and vice versa.

To explicitly create a copy of a NumPy array, you can use the copy() method.
#------------------------------------------------------------------------------
#View in NumPy:
A view is a new array that refers to the same data as the original array. 
It is a shallow copy in the sense that it shares the same data buffer as 
the original array.

Modifying the view will affect the original array, and changes made to the original 
array will be reflected in the view.

Views can be created using slicing or using the view() method.


In [135]:
var = np.array([15,8,3,5,90])
cpy = var.copy()
print(var)
print()
cpy[2] = 7
print(cpy)

[15  8  3  5 90]

[15  8  7  5 90]


In [147]:
var = np.array([15,8,3,5,90])
vew = var.view()
vew[1] = 7
print(var)
print()
print(vew)

[15  7  3  5 90]

[15  7  3  5 90]


## join & split in numpy 

#### Join array 

In [149]:
#1D Array
var1 = np.array([1,2,3,4])
var2 = np.array([11,12,13,14])

v_new = np.concatenate((var1,var2))
print(v_new)


[ 1  2  3  4 11 12 13 14]


In [151]:
#2D array
var1= np.array([[1,2,3,4],[5,6,7,8]])
var2= np.array([[11,12,13,14],[15,16,17,18]])


v_new = np.concatenate((var1,var2),axis = 1) # it concate column-wise meaning 0f 1 is column
print(var1.ndim)
print()
print(v_new)

2

[[ 1  2  3  4 11 12 13 14]
 [ 5  6  7  8 15 16 17 18]]


In [152]:
#2D array
var1= np.array([[1,2,3,4],[5,6,7,8]])
var2= np.array([[11,12,13,14],[15,16,17,18]])


v_new = np.concatenate((var1,var2),axis = 0) # it concate row-wise meaning 0f 0 is row
print(var1.ndim)
print()
print(v_new)

2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]
 [15 16 17 18]]


### using Stack to join array 

In [157]:
#1D Array
var1 = np.array([1,2,3,4])
var2 = np.array([11,12,13,14])

var_axis = np.stack((var1,var2),axis = 0)


var_new = np.stack((var1,var2))

var_row = np.hstack((var1,var2))
var_col = np.vstack((var1,var2))
var_height = np.dstack((var1,var2))


print(var_new)
print()
print(var_row)
print()
print(var_col)
print()
print(var_height)



[[ 1  2  3  4]
 [11 12 13 14]]

[ 1  2  3  4 11 12 13 14]

[[ 1  2  3  4]
 [11 12 13 14]]

[[[ 1 11]
  [ 2 12]
  [ 3 13]
  [ 4 14]]]


### Split in numpy 

In [162]:
var = np.array([1,2,3,4])

print(var)
print()

splt = np.array_split(var,3)
print(splt)
print()

print(type(splt))
print()

print(splt[0])
print()

print(type(splt[0]))

[1 2 3 4]

[array([1, 2]), array([3]), array([4])]

<class 'list'>

[1 2]

<class 'numpy.ndarray'>


In [165]:
var = np.array([[1,2,3,4],[5,6,7,8]])

print(var)
print()

splt = np.array_split(var,3, axis = 0)
print(splt)
print()

print(type(splt))
print()

print(splt[0])
print()

print(type(splt[0]))

[[1 2 3 4]
 [5 6 7 8]]

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int64)]

<class 'list'>

[[1 2 3 4]]

<class 'numpy.ndarray'>


### Search in array in numpy 

In [166]:
var = np.array([1,2,3,4,5,6,7,8,3,1,5,8,9,2,4,5,4,1,3,6,4])

srch = np.where(var == 4)
print(srch)

(array([ 3, 14, 16, 20]),)


In [167]:
var = np.array([1,2,3,4,5,6,7,8,3,1,5,8,9,2,4,5,4,1,3,6,4])

srch = np.where((var%2) == 0)
print(srch)

(array([ 1,  3,  5,  7, 11, 13, 14, 16, 19, 20]),)


### Search_Sort in numpy array

It gives the index where the element is placed on array
It works only in sorted array

In [173]:
var = np.array([1,2,3,5,7,9,13,15,20,24,25,29])
        # index 0,1 2 3 4 5 6  7  8  9  10 11 
srchsot = np.searchsorted(var,19)
print(srchsot)

8


In [175]:
var = np.array([1,2,3,5,7,9,13,15,20,24,25,29])
        # index 0,1 2 3 4 5 6  7  8  9  10 11 
srchsot = np.searchsorted(var,4, side = "right")
print(srchsot)

3


In [178]:
var = np.array([1,2,3,5,7,9,13,15,20,24,25,29])
        # index 0,1 2 3 4 5 6  7  8  9  10 11 
srchsot = np.searchsorted(var,4 ,side = 'left')
print(srchsot)

3


In [182]:
# Creating a sorted NumPy array
arr = np.array([1, 3, 5, 7, 9])

# Using searchsorted to find the indices for insertion
indices = np.searchsorted(arr, 6, side='right')  # 'right' indicates to insert to the right of any existing entries of the same value
print(indices)
# Inserting the element 6 at the computed index
arr = np.insert(arr, indices, 6)

# Printing the updated array
print(arr)

3
[1 3 5 6 7 9]


### sort 

In [183]:
var = np.array([1,2,3,5,7,9,13,15,20,24,25,29])
srt = np.sort(var)
print(srt)

[ 1  2  3  5  7  9 13 15 20 24 25 29]


In [184]:
var = np.array(['s','h','a','h','b','a','z'])
print(np.sort(var))


['a' 'a' 'b' 'h' 'h' 's' 'z']


### Filter in numpy

In [186]:
var = np.array(['s','h','a','h','b','a','z'])
f = [True,False,True,True,False,True,True]

new_var = var[f]

print(new_var)


['s' 'a' 'h' 'a' 'z']


#### Shuffle in numpy 

In [188]:
var = np.array([1,2,3,5,7,9,13,15,20,24,25,29])
np.random.shuffle(var)
print(var)

[ 7  5  3 20  2 24  1 29 15 13  9 25]


In [189]:
var = np.array([1,2,3,5,7,9,13,15,20,24,25,29])
sfl = np.random.shuffle(var)
print(sfl)

None


It not allow to assign shuffle value to store in another variable

In [195]:
#unique => it remove the duplicate value
var = np.array([1,2,3,5,7,2,29,1,3,4])
unq = np.unique(var,return_index = True, return_counts = True)
print(unq)
# print(var)

(array([ 1,  2,  3,  4,  5,  7, 29]), array([0, 1, 2, 9, 3, 4, 6]), array([2, 2, 2, 1, 1, 1, 1]))


#### Resize in numpy  array

In [201]:
var = np.array([1,2,3,5,7,2])
rsz = np.resize(var,(2,3))
print(rsz)

[[1 2 3]
 [5 7 2]]


In [202]:
var = np.array([0,1,2,3,5,7,2])
rsz = np.resize(var,(2,3))
print(rsz)

[[0 1 2]
 [3 5 7]]


In [204]:
var = np.array([1,2,3,5,7,2])
rsz = np.resize(var,(3,1))
print(rsz)
print(var)

[[1]
 [2]
 [3]]
[1 2 3 5 7 2]


In [211]:
var = np.array([[1,2,3,5,7,2],[3,6,8,3,4,8]])
rsz = var.flatten()
print(rsz)

[1 2 3 5 7 2 3 6 8 3 4 8]


In [212]:
var = np.array([[1,2,3,5,7,2],[3,6,8,3,4,8]])
#[1,2,3,5,7,2],
#[3,6,8,3,4,8]
rsz = var.flatten(order = "F")
print(rsz)

[1 3 2 6 3 8 5 3 7 4 2 8]


In [213]:
var = np.array([[1,2,3,5,7,2],[3,6,8,3,4,8]])
#[1,2,3,5,7,2],
#[3,6,8,3,4,8]
rsz = var.flatten(order = "C")
print(rsz)

[1 2 3 5 7 2 3 6 8 3 4 8]


#### Ravel in numpy 

In [214]:
var = np.array([[1,2,3,5,7,2],[3,6,8,3,4,8]])
#[1,2,3,5,7,2],
#[3,6,8,3,4,8]
rsz = var.ravel(order = "C")
print(rsz)

[1 2 3 5 7 2 3 6 8 3 4 8]


In [215]:
var = np.array([[1,2,3,5,7,2],[3,6,8,3,4,8]])
#[1,2,3,5,7,2],
#[3,6,8,3,4,8]
rsz = var.ravel(order = "F")
print(rsz)

[1 3 2 6 3 8 5 3 7 4 2 8]


In [ ]:
NumPy, both the flatten and ravel functions are used to convert multi-dimensional 
arrays into one-dimensional arrays, but they have some subtle differences.

#flatten:
Returns a Copy: The flatten function always returns a copy of the original array,
ensuring that any changes made to the flattened array do not affect the original array.

Performance: As it involves copying all the elements into a new one-dimensional array,
it might be less efficient for large arrays compared to other methods that retain 
the original array structure.

#ravel:
Returns a View if Possible: The ravel function returns a flattened one-dimensional array
that may be a view of the original array. If no copy is required, it will return a view
to improve performance. However, if the array is non-contiguous in memory, a copy will
be made.

Memory Efficiency: When the array is contiguous in memory, ravel does not create a new
copy, making it more memory-efficient compared to flatten.

### Insert 

In [217]:
var = np.array([1,2,3,5,7,2])
rsz = np.insert(var,4,60)
print(rsz)
print(var)

[ 1  2  3  5 60  7  2]
[1 2 3 5 7 2]


In [ ]:
var = np.array([1,2,3,5,7,2])
rsz = np.insert(var,4,60)
print(rsz)
print(var)

In [223]:
var = np.array([1,2,3,5,7,2])
rsz = np.insert(var,(0,3),(100))
print(rsz)
print(var)

[100   1   2   3 100   5   7   2]
[1 2 3 5 7 2]


In [226]:
var = np.array([1,2,3,5,7,2])
rsz = np.insert(var,(6),8.5)
print(rsz)
print(var)

[1 2 3 5 7 2 8]
[1 2 3 5 7 2]


In [228]:
#axis 1 => means column
var = np.array([[1,2,3],[4,5,6]])
rsz = np.insert(var, 2 ,20, axis = 1)
print(rsz)
print(var)

[[ 1  2 20  3]
 [ 4  5 20  6]]
[[1 2 3]
 [4 5 6]]


In [229]:
#axis 1 => means row

var = np.array([[1,2,3],[4,5,6]])
rsz = np.insert(var, 2 ,20, axis = 0)
print(rsz)
print(var)

[[ 1  2  3]
 [ 4  5  6]
 [20 20 20]]
[[1 2 3]
 [4 5 6]]


### append 

In [231]:
var = np.array([1,2,3,5,7,2])
new = np.append(var, 30.7)
print(new)
print(type(new))
print(var)

[ 1.   2.   3.   5.   7.   2.  30.7]
<class 'numpy.ndarray'>
[1 2 3 5 7 2]


In [235]:
var = np.array([[1,2,3],[4,6,7]])
new = np.append(var, [[10,11,12]], axis = 0)
print(new)
print()
print(var)

[[ 1  2  3]
 [ 4  6  7]
 [10 11 12]]

[[1 2 3]
 [4 6 7]]


In [239]:
var = np.array([[1, 2, 3], [4, 6, 7]])
# Transpose the array to match the dimensions
new = np.append(var, [[101], [111]], axis=1)
print(new)
print(var.ndim)
print(var)

[[  1   2   3 101]
 [  4   6   7 111]]
2
[[1 2 3]
 [4 6 7]]


In [245]:
var = np.array([12, 25, 31,46, 67, 77])
# Transpose the array to match the dimensions
new = np.delete(var,2)

print(var)
print()
print(new)

[12 25 31 46 67 77]

[12 25 46 67 77]


### Matrix

In [246]:
#Woking with array
var1 = np.array([1,2,3])
var2 = np.array([1,2,3])
print(var1+var2)

[2 4 6]


In [248]:
var1 = np.array([1,2,3])
var2 = np.array([1,2,3])
print(var1-var2)

[0 0 0]


In [249]:
var1 = np.array([1,2,3])
var2 = np.array([1,2,3])
print(var1/var2)

[1. 1. 1.]


In [250]:
var1 = np.array([1,2,3])
var2 = np.array([1,2,3])
print(var1 % var2)

[0 0 0]


In [251]:
var1 = np.array([1,2,3])
var2 = np.array([1,2,3])
print(var1 * var2)

[1 4 9]


In [256]:
#working with matrix
### using .dot() 
var1 = np.matrix([[1,2],[3,4]])
var2 = np.matrix([[1,2],[3,2]])
print(var1.dot(var2))

[[ 7  6]
 [15 14]]


In [258]:
#working with matrix
### using .dot() 
var1 = np.matrix([[1,2],[3,4]])
var2 = np.matrix([[1,2],[31,21]])
# print(var1.dot(var2))
print(var1 + var2)

[[ 2  4]
 [34 25]]


In [259]:
#working with matrix
### using .dot() 
var1 = np.matrix([[1,2],[3,4]])
var2 = np.matrix([[1,2],[31,21]])
# print(var1.dot(var2))
print(var1 - var2)

[[  0   0]
 [-28 -17]]


### Matrix transpose Fuction

In [261]:
var = np.array([[1, 2, 3], [4, 6, 7]])
new_var = np.transpose(var)

print(var)
print()
print(new_var)


[[1 2 3]
 [4 6 7]]

[[1 4]
 [2 6]
 [3 7]]


In [266]:
# using T for transpose
var = np.array([[1, 2, 3], [4, 6, 7]])
print(var.T) # only we can apply not store


[[1 4]
 [2 6]
 [3 7]]


In [271]:

var = np.array([[1, 2, 3,5], [4, 6, 7,10]])
print(np.swapaxes(var, 0,1))


[[ 1  4]
 [ 2  6]
 [ 3  7]
 [ 5 10]]


In [2]:
import numpy as np
var = np.array([[1, 2, 3,4], [4, 6, 7,9]])
print(np.swapaxes(var, 1,0))


[[1 4]
 [2 6]
 [3 7]
 [4 9]]
